### ISSUE TITLE
Here is the error I run into when it is compiling with python support

### ISSUE THREAD

**Issue by SJMitchell** [mkosolofski/Coding_With_VIM#2]
if_python.c:67:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make[1]: **\* [objects/if_python.o] Error 1
make[1]: Leaving directory `/tmp/vimSrc/src'
make: *** [first] Error 2
Installing Vim
Starting make in the src directory.
If there are problems, cd to the src directory and run make there
cd src && make install
make[1]: Entering directory`/tmp/vimSrc/src'
gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -I/usr/include/python2.7 -DPYTHON_HOME='"/usr"' -pthread -fPIE  -o objects/if_python.o if_python.c
if_python.c:67:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make[1]: **\* [objects/if_python.o] Error 1
make[1]: Leaving directory `/tmp/vimSrc/src'
make: **\* [install] Error 2
update-alternatives: error: alternative path /usr/local/bin/vim doesn't exist
update-alternatives: error: alternative path /usr/local/bin/vim doesn't exist
Installing Plugins - Just kidding this needs to be adjusted :p

**Comment by mkosolofski** [comment]
I have updated the provision script which should solve your problem.
